//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolidWorksProjectSwitcher.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SolidWorksProjectSwitcher.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current SolidWorks Project.
        /// </summary>
        public static string CurrentSolidWorksProject {
            get {
                return ResourceManager.GetString("CurrentSolidWorksProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error!.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maybe the path in the configuration file &quot;solidworkspath.ini&quot; is incorrect!.
        /// </summary>
        public static string ErrorCouldNotStartSolidWorksMessage {
            get {
                return ResourceManager.GetString("ErrorCouldNotStartSolidWorksMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not start SolidWorks!.
        /// </summary>
        public static string ErrorCouldNotStartSolidWorksTitle {
            get {
                return ResourceManager.GetString("ErrorCouldNotStartSolidWorksTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %1 could not be deleted..
        /// </summary>
        public static string ErrorDeletionFailedMessage {
            get {
                return ResourceManager.GetString("ErrorDeletionFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletion failed!.
        /// </summary>
        public static string ErrorDeletionFailedTitle {
            get {
                return ResourceManager.GetString("ErrorDeletionFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A directory with the given name already exists!.
        /// </summary>
        public static string ErrorDirectoryExistsMessage {
            get {
                return ResourceManager.GetString("ErrorDirectoryExistsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory exists.
        /// </summary>
        public static string ErrorDirectoryExistsTitle {
            get {
                return ResourceManager.GetString("ErrorDirectoryExistsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory-name contains invalid characters!.
        /// </summary>
        public static string ErrorDirectoryNameContainsInvalidCharacters {
            get {
                return ResourceManager.GetString("ErrorDirectoryNameContainsInvalidCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found!.
        /// </summary>
        public static string ErrorFileNotFound {
            get {
                return ResourceManager.GetString("ErrorFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The directory that is associated to the selected entry could not be found!.
        /// </summary>
        public static string ErrorSelectedAssociatedDirectoryNotFound {
            get {
                return ResourceManager.GetString("ErrorSelectedAssociatedDirectoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected directory &apos;%1&apos; could not be found!.
        /// </summary>
        public static string ErrorSelectedDirectoryNotFound {
            get {
                return ResourceManager.GetString("ErrorSelectedDirectoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not start SolidWorks because the configuration file &quot;solidworkspath.ini&quot; could not be found!.
        /// </summary>
        public static string ErrorSolidWorksPathIniMissing {
            get {
                return ResourceManager.GetString("ErrorSolidWorksPathIniMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not check if SolidWorks is running because the configuration file &quot;solidworksprocessname.ini&quot; was not found!
        ///To prevent errors, it is assumed that SolidWorks is still running..
        /// </summary>
        public static string ErrorSolidWorksProcessNameIniMissing {
            get {
                return ResourceManager.GetString("ErrorSolidWorksProcessNameIniMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading solidworksprojectfolder.ini failed!
        ///Make sure the file exists and the path is correct!.
        /// </summary>
        public static string ErrorSolidWorksProjectFile {
            get {
                return ResourceManager.GetString("ErrorSolidWorksProjectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SolidWorks project folder path must be set in solidworksprojectfolder.ini!
        ///For example: &apos;C:\swlocal&apos;.
        /// </summary>
        public static string ErrorSolidWorksProjectPathNotSet {
            get {
                return ResourceManager.GetString("ErrorSolidWorksProjectPathNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name-prefix:.
        /// </summary>
        public static string NamePrefix {
            get {
                return ResourceManager.GetString("NamePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;New SolidWorks project&gt;.
        /// </summary>
        public static string NewSolidWorksProject {
            get {
                return ResourceManager.GetString("NewSolidWorksProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other SolidWorks projects.
        /// </summary>
        public static string OtherSolidWorksProjects {
            get {
                return ResourceManager.GetString("OtherSolidWorksProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename current SolidWorks project:.
        /// </summary>
        public static string RenameCurrentSolidWorksProject {
            get {
                return ResourceManager.GetString("RenameCurrentSolidWorksProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SLDWorks is still running!.
        /// </summary>
        public static string SolidWorksRunning {
            get {
                return ResourceManager.GetString("SolidWorksRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As long as SLDWorks is running the directory can not be switched or deleted..
        /// </summary>
        public static string SolidWorksRunningInfo {
            get {
                return ResourceManager.GetString("SolidWorksRunningInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start SolidWorks after switch.
        /// </summary>
        public static string StartSolidWorksAfterSwitch {
            get {
                return ResourceManager.GetString("StartSolidWorksAfterSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch.
        /// </summary>
        public static string Switch {
            get {
                return ResourceManager.GetString("Switch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch and delete current.
        /// </summary>
        public static string SwitchAndDelete {
            get {
                return ResourceManager.GetString("SwitchAndDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SolidWorks Project Switcher.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Unknown&gt;.
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning!.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete &quot;%1&quot;?.
        /// </summary>
        public static string WarningDeleteConfirmationMessage {
            get {
                return ResourceManager.GetString("WarningDeleteConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the current %1 directory?.
        /// </summary>
        public static string WarningDeleteDirectory {
            get {
                return ResourceManager.GetString("WarningDeleteDirectory", resourceCulture);
            }
        }
    }
}
